import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const products: Product[] = [
  {
    id: '1',
    name: 'Tênis Vibe Runner',
    description: 'Corra com estilo e conforto.',
    longDescription: 'O Tênis Vibe Runner foi desenhado para corredores urbanos que não abrem mão do estilo. Com tecnologia de amortecimento avançada e um design minimalista, ele é perfeito para o asfalto e para o seu dia a dia. Feito com materiais reciclados.',
    price: 349.9,
    images: [getImageUrl('tenis-preto-1'), getImageUrl('tenis-preto-2')],
    category: 'tênis',
    rating: 4.5,
    reviews: 120,
  },
  {
    id: '2',
    name: 'Tênis Classic White',
    description: 'O clássico que nunca sai de moda.',
    longDescription: 'Simples, elegante e versátil. O Tênis Classic White é a peça que faltava no seu guarda-roupa. Combina com tudo, desde um look casual até um mais arrumado. Sua construção em couro sintético garante durabilidade e fácil limpeza.',
    price: 279.9,
    images: [getImageUrl('tenis-branco-1'), getImageUrl('tenis-branco-2')],
    category: 'tênis',
    rating: 4.8,
    reviews: 250,
  },
  {
    id: '3',
    name: 'Tênis Urban Skate',
    description: 'Para as pistas e para a rua.',
    longDescription: 'Inspirado na cultura do skate, o Tênis Urban Skate oferece durabilidade e aderência. Seu solado de borracha vulcanizada e cabedal reforçado aguentam qualquer manobra, enquanto o design sóbrio em cinza mantém seu estilo em alta.',
    price: 319.9,
    images: [getImageUrl('tenis-cinza-1'), getImageUrl('tenis-cinza-2')],
    category: 'tênis',
    rating: 4.6,
    reviews: 95,
  },
  {
    id: '4',
    name: 'Tênis High-Top Impulse',
    description: 'Atitude e presença em cada passo.',
    longDescription: 'O Tênis High-Top Impulse é para quem quer se destacar. Com seu design de cano alto e contraste preto e branco, ele traz uma vibe dos anos 90 com um toque moderno. Perfeito para compor looks cheios de personalidade.',
    price: 399.9,
    images: [getImageUrl('tenis-cano-alto-1'), getImageUrl('tenis-cano-alto-2')],
    category: 'tênis',
    rating: 4.7,
    reviews: 150,
  },
  {
    id: '5',
    name: 'Camiseta Minimal Branca',
    description: 'A base para qualquer look.',
    longDescription: 'Feita com algodão orgânico de alta qualidade, a Camiseta Minimal Branca é essencial. Seu corte perfeito e tecido macio proporcionam conforto o dia todo. Uma peça-chave para um guarda-roupa inteligente e minimalista.',
    price: 119.9,
    images: [getImageUrl('camiseta-branca-1')],
    category: 'roupas',
    rating: 4.9,
    reviews: 300,
  },
  {
    id: '6',
    name: 'Camiseta Estampada "VIBE"',
    description: 'Expresse sua vibe com estilo.',
    longDescription: 'Mais do que uma camiseta, uma declaração. A estampa "VIBE" em design minimalista sobre o tecido preto de alta qualidade faz desta peça um item único. Mostre sua personalidade sem dizer uma palavra.',
    price: 139.9,
    images: [getImageUrl('camiseta-preta-1')],
    category: 'roupas',
    rating: 4.8,
    reviews: 180,
  },
  {
    id: '7',
    name: 'Moletom com Capuz Essencial',
    description: 'Conforto e estilo para dias frios.',
    longDescription: 'O Moletom com Capuz Essencial é seu companheiro perfeito para o inverno. Feito de moletom flanelado, ele é quente, confortável e estiloso. O design preto básico com detalhes de alta qualidade o torna uma peça durável e versátil.',
    price: 299.9,
    images: [getImageUrl('moletom-preto-1')],
    category: 'roupas',
    rating: 4.9,
    reviews: 210,
  },
  {
    id: '8',
    name: 'Calça Jeans Preta Slim',
    description: 'Versatilidade e caimento perfeito.',
    longDescription: 'Uma boa calça jeans preta é indispensável. A nossa versão slim tem o caimento perfeito, modelando o corpo sem restringir os movimentos. O tecido com um toque de elastano garante o conforto, seja para o trabalho ou para o lazer.',
    price: 249.9,
    images: [getImageUrl('calca-jeans-1')],
    category: 'roupas',
    rating: 4.6,
    reviews: 140,
  },
];
