
export type SizeInfo = {
  size: string;
  stock: number;
};

export type Review = {
  id: string;
  userName: string;
  userAvatar?: string;
  rating: number;
  comment: string;
  date: string;
  isAutoGenerated?: boolean; // Flag para identificar avaliações do gerador
  status?: 'pending' | 'approved';
  user_id?: string;
};

export type Variant = {
  id: string;
  color: string;
  colorHex: string;
  price: number;
  oldPrice?: number;
  acrescimoCartao?: number;
  images: string[];
  imageNames?: string[]; // Nome correspondente a cada imagem (para mochilas)
  sizes: SizeInfo[];
};

export type Product = {
  id: string;
  name: string;
  brand?: string;
  description: string; // Short description for cards
  longDescription: string;
  gender: 'masculino' | 'feminino' | 'unissex';
  category: 'calcados' | 'roupas' | 'acessorios' | 'perfumes';
  subCategory?: string;
  variants: Variant[];
  rating: number;
  reviewsCount?: number;
  reviews?: Review[];
  status: 'ativo' | 'inativo';
  tags?: string[];
  quality?: 'Essential' | 'Select' | 'Elite' | 'Ultra';
  isImported?: boolean; // Selo de produto importado
  showSizeChart?: boolean; // Exibir tabela de medidas
  origin?: string; // Campo de origem para uso do admin
  hasGift?: boolean; // Opção de brinde
};

export type CartItem = {
  product: Product;
  variant: Variant;
  size: string;
  quantity: number;
  selectedImage?: string; // Add selectedImage for backpacks
  displayName?: string; // Nome a ser exibido no carrinho (para mochilas)
  giftChoice?: 'dourada' | 'prata'; // Cor do brinde
};

export type UserProfile = {
  uid: string;
  name: string;
  email: string;
  address?: string;
  phone?: string;
  points?: number;
  reviewedProductIds?: string[];
  lastPointsUpdate?: string;
};

export type OrderItem = {
    productId: string;
    productName: string;
    variantColor: string;
    size: string;
    quantity: number;
    price: number;
    imageUrl: string;
    giftChoice?: 'dourada' | 'prata';
}

export type OrderStatus =
  | 'Pedido confirmado'
  | 'Pedido em separação'
  | 'Pedido em transporte'
  | 'Saiu para entrega'
  | 'Pedido entregue';

export type Order = {
  id: string;
  user_id: string;
  originalSessionId?: string; // ID da sessão de checkout ou do pagamento
  customerInfo: {
    name: string;
    email: string;
    phone?: string;
  },
  items: OrderItem[];
  orderDate: string; // ISO String
  totalAmount: number;
  shippingAddress: string;
  status: OrderStatus;
  couponCode?: string;
  discountAmount?: number;
  paymentMethod: 'credit_card' | 'debit_card' | 'ticket' | 'account_money' | 'pix';
}

export type Coupon = {
  id: string;
  code: string;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  expiryDate?: string; // ISO String
  isActive: boolean;
  usageCount?: number;
  minSpend?: number;
}
