
'use client';

import React, { useState, useMemo, useEffect } from 'react';
import { Star, StarHalf, User, Lock, MessageCircle, Send, Loader2 } from 'lucide-react';
import { Review, Order } from '@/lib/types';
import { Button } from './ui/button';
import { Avatar, AvatarFallback } from './ui/avatar';
import { Separator } from './ui/separator';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { cn } from '@/lib/utils';
import { useSearchParams } from 'next/navigation';
import { useUser, useFirestore } from '@/firebase';
import { collectionGroup, query, where, getDocs, doc, updateDoc, arrayUnion, increment, getDoc } from 'firebase/firestore';
import { Textarea } from './ui/textarea';
import { useToast } from '@/hooks/use-toast';

interface ProductReviewsProps {
  reviews?: Review[];
  productId?: string;
}

const ReviewForm = ({ productId, onFinish }: { productId: string, onFinish: () => void }) => {
    const { user } = useUser();
    const firestore = useFirestore();
    const { toast } = useToast();
    const [rating, setRating] = useState(5);
    const [comment, setComment] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!user || !firestore || !productId) return;
        if (!comment.trim()) {
            toast({ variant: 'destructive', title: "Atenção", description: "Por favor, escreva um comentário." });
            return;
        }

        setIsSubmitting(true);
        try {
            const newReview: Review = {
                id: `user_${Date.now()}`,
                userId: user.uid,
                userName: user.displayName || 'Cliente PISA VIBE',
                rating,
                comment,
                date: new Date().toISOString(),
                status: 'pending',
                isAutoGenerated: false
            };

            const productRef = doc(firestore, 'products', productId);
            await updateDoc(productRef, {
                reviews: arrayUnion(newReview)
            });

            // Adicionar pontos ao usuário
            const userRef = doc(firestore, 'users', user.uid);
            await updateDoc(userRef, {
                points: increment(5)
            });

            toast({ title: "Obrigado pela sua avaliação!", description: "Sua avaliação foi enviada e será analisada. Você ganhou +5 pontos!" });
            onFinish();
        } catch (error) {
            console.error("Error submitting review:", error);
            toast({ variant: 'destructive', title: "Erro", description: "Não foi possível enviar sua avaliação." });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="bg-secondary/30 p-6 rounded-lg border-2 border-dashed border-primary/20 animate-in fade-in slide-in-from-top-4">
            <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
                <MessageCircle className="h-5 w-5" />
                Sua Avaliação
            </h3>
            <div className="space-y-4">
                <div>
                    <p className="text-sm font-medium mb-2">Nota:</p>
                    <div className="flex gap-1">
                        {[1, 2, 3, 4, 5].map((star) => (
                            <button
                                key={star}
                                type="button"
                                onClick={() => setRating(star)}
                                className="focus:outline-none transition-transform hover:scale-110"
                            >
                                <Star className={cn("h-8 w-8", star <= rating ? "fill-primary text-primary" : "text-muted-foreground")} />
                            </button>
                        ))}
                    </div>
                </div>
                <div>
                    <p className="text-sm font-medium mb-2">Comentário:</p>
                    <Textarea 
                        placeholder="Conte-nos o que achou do produto..." 
                        value={comment}
                        onChange={(e) => setComment(e.target.value)}
                        className="bg-background min-h-[100px]"
                        required
                    />
                </div>
                <Button type="submit" disabled={isSubmitting} className="w-full">
                    {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Send className="h-4 w-4 mr-2" />}
                    Enviar Avaliação
                </Button>
            </div>
        </form>
    );
};

export function ProductReviews({ reviews = [], productId }: ProductReviewsProps) {
  const searchParams = useSearchParams();
  const { user } = useUser();
  const firestore = useFirestore();
  const [visibleCount, setVisibleCount] = useState(5);
  const [isEligible, setIsEligible] = useState(false);
  const [hasReviewed, setHasReviewed] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [isLoadingEligibility, setIsLoadingEligibility] = useState(false);

  useEffect(() => {
    const checkEligibility = async () => {
        if (!user || !firestore || !productId) return;
        setIsLoadingEligibility(true);
        try {
            // Verificar se o usuário comprou o produto e se está entregue
            const ordersRef = collectionGroup(firestore, 'orders');
            const q = query(
                ordersRef, 
                where('userId', '==', user.uid),
                where('status', '==', 'Pedido entregue')
            );
            const snapshot = await getDocs(q);
            
            const deliveredOrders = snapshot.docs.map(d => d.data() as Order);
            const boughtThisProduct = deliveredOrders.some(order => 
                order.items.some(item => item.productId === productId)
            );

            setIsEligible(boughtThisProduct);

            // Verificar se já avaliou
            const productRef = doc(firestore, 'products', productId);
            const productSnap = await getDoc(productRef);
            if (productSnap.exists()) {
                const data = productSnap.data();
                const existingReviews = Array.isArray(data.reviews) ? data.reviews : [];
                const alreadyReviewed = existingReviews.some((r: any) => r.userId === user.uid);
                setHasReviewed(alreadyReviewed);
            }

            // Se vier do fluxo de convite (?review=true) e for elegível
            if (boughtThisProduct && !hasReviewed && searchParams.get('review') === 'true') {
                setShowForm(true);
            }
        } catch (error) {
            console.error("Error checking review eligibility:", error);
        } finally {
            setIsLoadingEligibility(false);
        }
    };

    checkEligibility();
  }, [user, firestore, productId, searchParams, hasReviewed]);

  const safeReviews = useMemo(() => {
    // Filtrar apenas aprovadas ou automáticas, exceto para o próprio autor (para ver que enviou)
    const all = Array.isArray(reviews) ? reviews : [];
    return all.filter(r => 
        r.status === 'approved' || 
        r.isAutoGenerated || 
        (user && r.userId === user.uid)
    );
  }, [reviews, user]);

  const averageRating = useMemo(() => {
    const approvedReviews = safeReviews.filter(r => r.status === 'approved' || r.isAutoGenerated);
    if (approvedReviews.length === 0) return 0;
    const sum = approvedReviews.reduce((acc, review) => acc + review.rating, 0);
    return Number((sum / approvedReviews.length).toFixed(1));
  }, [safeReviews]);

  const sortedReviews = useMemo(() => {
    return [...safeReviews].sort((a, b) => {
      const dateA = a.date ? new Date(a.date).getTime() : 0;
      const dateB = b.date ? new Date(b.date).getTime() : 0;
      return dateB - dateA;
    });
  }, [safeReviews]);

  const displayedReviews = sortedReviews.slice(0, visibleCount);

  const renderStars = (rating: number, className?: string) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 !== 0;

    for (let i = 1; i <= 5; i++) {
      if (i <= fullStars) {
        stars.push(<Star key={i} className={cn("h-4 w-4 fill-primary text-primary", className)} />);
      } else if (i === fullStars + 1 && hasHalfStar) {
        stars.push(<StarHalf key={i} className={cn("h-4 w-4 fill-primary text-primary", className)} />);
      } else {
        stars.push(<Star key={i} className={cn("h-4 w-4 text-muted-foreground", className)} />);
      }
    }
    return stars;
  };

  return (
    <section id="avaliacoes" className="mt-16 border-t pt-12">
      <div className="flex flex-col gap-8 md:flex-row md:items-start md:justify-between">
        <div>
          <h2 className="font-headline text-2xl font-bold">Avaliações</h2>
          <div className="mt-2 flex items-center gap-4">
            <div className="flex items-center">
              {renderStars(averageRating, "h-5 w-5")}
            </div>
            <p className="text-lg font-semibold">
              {averageRating > 0 ? `${averageRating} de 5` : "Sem avaliações"}
            </p>
            <p className="text-sm text-muted-foreground">
              ({safeReviews.length} {safeReviews.length === 1 ? "avaliação" : "avaliações"})
            </p>
          </div>
        </div>

        <div className="flex flex-col items-center md:items-end gap-2">
          {isLoadingEligibility ? (
              <Button disabled variant="outline" className="gap-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Verificando...
              </Button>
          ) : isEligible && !hasReviewed ? (
              <Button onClick={() => setShowForm(!showForm)} variant={showForm ? "outline" : "default"} className="gap-2">
                  <MessageCircle className="h-4 w-4" />
                  {showForm ? "Cancelar Avaliação" : "Avaliar produto"}
              </Button>
          ) : (
              <>
                <Button disabled variant="outline" className="gap-2 opacity-60">
                    <Lock className="h-4 w-4" />
                    Avaliar produto
                </Button>
                <p className="text-[11px] md:text-xs text-muted-foreground text-center md:text-right max-w-[250px] leading-tight">
                    {hasReviewed ? "Você já avaliou este produto." : "Somente clientes que compraram e receberam o produto podem deixar uma avaliação."}
                </p>
              </>
          )}
        </div>
      </div>

      <div className="mt-10 space-y-8">
        {showForm && productId && (
            <ReviewForm productId={productId} onFinish={() => { setShowForm(false); setHasReviewed(true); }} />
        )}

        {displayedReviews.length > 0 ? (
          <>
            {displayedReviews.map((review) => (
              <div key={review.id} className="flex flex-col gap-4 relative">
                {review.status === 'pending' && (
                    <Badge variant="secondary" className="absolute top-0 right-0 text-[10px] bg-amber-100 text-amber-800 border-amber-200">
                        Em análise
                    </Badge>
                )}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Avatar className="h-10 w-10 border">
                      <AvatarFallback>
                        <User className="h-5 w-5 text-muted-foreground" />
                      </AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-semibold text-sm">{review.userName}</p>
                      <div className="flex items-center mt-0.5">
                        {renderStars(review.rating, "h-3 w-3")}
                      </div>
                    </div>
                  </div>
                  <time className="text-xs text-muted-foreground">
                    {review.date ? format(new Date(review.date), "dd 'de' MMM, yyyy", { locale: ptBR }) : ''}
                  </time>
                </div>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {review.comment}
                </p>
                <Separator className="mt-4" />
              </div>
            ))}

            {visibleCount < safeReviews.length && (
              <div className="flex justify-center pt-4">
                <Button 
                  variant="outline" 
                  onClick={() => setVisibleCount(prev => prev + 5)}
                >
                  Ver mais avaliações
                </Button>
              </div>
            )}
          </>
        ) : (
          <div className="flex flex-col items-center justify-center py-12 text-center border-2 border-dashed rounded-lg">
            <p className="text-muted-foreground">Ainda não há avaliações para este produto.</p>
            <p className="text-sm text-muted-foreground mt-1">As avaliações são coletadas após a confirmação da entrega.</p>
          </div>
        )}
      </div>
    </section>
  );
}
